### ISSUE TITLE
Taking too long to load

### ISSUE THREAD

**Issue by Mennaruuk** [AJAYK-01/Reactube#2]
My experience is that it takes approximately 48 seconds for the homepage videos to appear. Until then, everything looks like this:
![image](https://user-images.githubusercontent.com/52135169/105796443-e0ea1800-5f5c-11eb-94bb-8b05123186ff.png)

Maybe an issue with async calls?

**Comment by Mennaruuk** [comment]
I noticed this issue also occurs every time I search. So for every search, there is a ~48-second waiting time.

**Comment by Mennaruuk** [comment]
An important announcement regarding Invidious: "[invidio.us is now deprecated, invidious.io is the new domain.](https://github.com/iv-org/invidious/issues/1694)"

"The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/"

**Comment by AJAYK-01** [comment]
Seems like the primary invidious instance used in the repo is down right now, and its loading after about 40 secs because the fallback instance used is up.
I'll update it :)

**Comment by Mennaruuk** [comment]
THANK YOU!!!

**Comment by AJAYK-01** [comment]
> THANK YOU!!!

How did you find this project though 😅 ?

**Comment by Mennaruuk** [comment]
There are only like 30 packages under the [Invidious tag.](https://github.com/topics/invidious) Yours happens to be one of them.
